import { Restaurant, MenuItem } from '../types';

export const INITIAL_RESTAURANTS: Restaurant[] = [
  {
    id: 'rest-technopark-malabar-spices',
    name: 'Malabar Spices & Grill Co.',
    tagline: 'Modern Coastal Grills, High-Protein Bowls & Nadan Biryanis',
    coverImage: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=1000&auto=format&fit=crop&q=80',
    logo: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=200&auto=format&fit=crop&q=80',
    isPartner: true,
    cuisines: ['Kerala Traditional', 'Charcoal Grills', 'Healthy Bowls', 'Biryani'],
    rating: 4.8,
    ratingCount: 1420,
    area: 'Technopark & Kazhakkoottam',
    address: 'Near Main Gate, Technopark Phase 1, Kazhakkoottam, Thiruvananthapuram',
    district: 'Thiruvananthapuram',
    lat: 8.5582,
    lng: 76.8812,
    distanceKm: 1.2,
    avgPrepTimeMin: 14,
    avgDeliveryTimeMin: 22,
    priceForTwo: 350,
    isOpen: true,
    openingHours: '11:00 AM - 11:30 PM',
    pureVeg: false,
    featuredTags: ['fitness', 'high-protein', 'kerala-favs', 'quick15'],
    menuCategories: ['Chef Specials', 'High Protein Bowls', 'Quick 15 Express', 'Travancore Curries', 'Breads & Rice', 'Beverages'],
    phone: '+91 471 270 9988',
    reviews: [
      {
        id: 'rev-1',
        restaurantId: 'rest-technopark-malabar-spices',
        userName: 'Arjun Menon (Software Architect)',
        rating: 5,
        date: 'Yesterday',
        comment: 'The Grilled Chicken Protein Bowl is a game changer during busy coding sprints at Technopark! Super fast delivery in 18 minutes.',
        foodItemName: 'Charred Chicken Protein Power Bowl',
        helpfulCount: 24
      },
      {
        id: 'rev-2',
        restaurantId: 'rest-technopark-malabar-spices',
        userName: 'Dr. Ananya Nair',
        rating: 4.9,
        date: '3 days ago',
        comment: 'Authentic pepper spices without being greasy. You can clearly taste the fresh coconut oil and curry leaves.',
        foodItemName: 'Travancore Pepper Chicken Roast',
        helpfulCount: 15
      }
    ],
    menu: [
      {
        id: 'item-charred-chicken-bowl',
        restaurantId: 'rest-technopark-malabar-spices',
        restaurantName: 'Malabar Spices & Grill Co.',
        name: 'Charred Chicken Protein Power Bowl',
        description: 'Tender chicken breast marinated in crushed pepper & Kerala herbs, served over brown rice, roasted broccoli & minted yogurt drizzle.',
        price: 249,
        originalPrice: 299,
        image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=600&auto=format&fit=crop&q=80',
        isVeg: false,
        isBestseller: true,
        isQuick15: true,
        prepTimeMinutes: 12,
        rating: 4.9,
        ratingCount: 520,
        category: 'High Protein Bowls',
        cuisine: 'Kerala Grill',
        tags: ['fitness', 'high-protein', 'healthy', 'less-oil', 'quick15'],
        spiceLevel: 2,
        nutrition: {
          calories: 420,
          proteinGrams: 38,
          carbsGrams: 32,
          fatGrams: 9,
          fiberGrams: 6,
          sugarGrams: 3,
          sodiumMg: 380
        },
        available: true,
        optionGroups: [
          {
            id: 'opt-rice-base',
            title: 'Choose Rice Base',
            required: true,
            minSelect: 1,
            maxSelect: 1,
            options: [
              { id: 'opt-brown-rice', name: 'Steamed Brown Rice', priceDelta: 0 },
              { id: 'opt-kerala-matta', name: 'Kerala Matta Rice', priceDelta: 0 },
              { id: 'opt-quinoa-grain', name: 'Organic Quinoa Bed', priceDelta: 30 }
            ]
          },
          {
            id: 'opt-addons',
            title: 'Add-ons',
            required: false,
            minSelect: 0,
            maxSelect: 2,
            options: [
              { id: 'opt-extra-egg', name: 'Add Boiled Egg', priceDelta: 20 },
              { id: 'opt-extra-chicken', name: 'Extra Grilled Chicken (+50g)', priceDelta: 59 }
            ]
          }
        ]
      },
      {
        id: 'item-kallu-shappu-chicken-roast',
        restaurantId: 'rest-technopark-malabar-spices',
        restaurantName: 'Malabar Spices & Grill Co.',
        name: 'Travancore Pepper Chicken Roast',
        description: 'Slow-roasted succulent country chicken tossed with shallots, crushed black tellicherry pepper and curry leaves.',
        price: 219,
        originalPrice: 249,
        image: 'https://images.unsplash.com/photo-1598515214211-89d3c73ae83b?w=600&auto=format&fit=crop&q=80',
        isVeg: false,
        isBestseller: true,
        isQuick15: true,
        prepTimeMinutes: 10,
        rating: 4.8,
        ratingCount: 380,
        category: 'Chef Specials',
        cuisine: 'Kerala Traditional',
        tags: ['kerala-favs', 'high-protein', 'spicy-lovers', 'quick15'],
        spiceLevel: 3,
        nutrition: {
          calories: 360,
          proteinGrams: 32,
          carbsGrams: 8,
          fatGrams: 14,
          sodiumMg: 420
        },
        available: true
      },
      {
        id: 'item-malabar-fish-curry',
        restaurantId: 'rest-technopark-malabar-spices',
        restaurantName: 'Malabar Spices & Grill Co.',
        name: 'Neymeen (King Fish) Coconut Curry',
        description: 'Fresh catch kingfish simmered in light coconut milk, kudampuli (cambodge) and fresh ginger.',
        price: 289,
        originalPrice: 320,
        image: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=600&auto=format&fit=crop&q=80',
        isVeg: false,
        isBestseller: false,
        isQuick15: false,
        prepTimeMinutes: 15,
        rating: 4.7,
        ratingCount: 210,
        category: 'Travancore Curries',
        cuisine: 'Kerala Seafood',
        tags: ['kerala-favs', 'high-protein', 'gluten-free', 'dairy-free'],
        spiceLevel: 2,
        nutrition: {
          calories: 310,
          proteinGrams: 29,
          carbsGrams: 6,
          fatGrams: 12
        },
        available: true
      },
      {
        id: 'item-appam-egg-roast-combo',
        restaurantId: 'rest-technopark-malabar-spices',
        restaurantName: 'Malabar Spices & Grill Co.',
        name: 'Soft Laced Appam with Nadan Egg Roast (3 Pcs)',
        description: 'Crispy-edged fermented rice hoppers paired with caramelised onion and double spiced farm egg gravy.',
        price: 139,
        originalPrice: 160,
        image: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=600&auto=format&fit=crop&q=80',
        isVeg: false,
        isBestseller: true,
        isQuick15: true,
        prepTimeMinutes: 8,
        rating: 4.8,
        ratingCount: 430,
        category: 'Quick 15 Express',
        cuisine: 'Kerala Traditional',
        tags: ['budget', 'quick15', 'kerala-favs', 'breakfast', 'dinner'],
        spiceLevel: 2,
        nutrition: {
          calories: 340,
          proteinGrams: 16,
          carbsGrams: 48,
          fatGrams: 10
        },
        available: true
      }
    ]
  },
  {
    id: 'rest-kowdiar-green-leaf-organics',
    name: 'Green Leaf Botanica & Cafe',
    tagline: 'Clean Eatery, Cold-Pressed Squeezes & Low-Calorie Bowls',
    coverImage: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=1000&auto=format&fit=crop&q=80',
    logo: 'https://images.unsplash.com/photo-1498837167922-ddd27525d352?w=200&auto=format&fit=crop&q=80',
    isPartner: true,
    cuisines: ['Healthy Continental', 'Vegan', 'Superfood Bowls', 'Beverages'],
    rating: 4.9,
    ratingCount: 980,
    area: 'Kowdiar & Vellayambalam',
    address: 'Kuravankonam - Kowdiar Avenue, Thiruvananthapuram',
    district: 'Thiruvananthapuram',
    lat: 8.5241,
    lng: 76.9582,
    distanceKm: 2.1,
    avgPrepTimeMin: 12,
    avgDeliveryTimeMin: 20,
    priceForTwo: 420,
    isOpen: true,
    openingHours: '7:30 AM - 10:30 PM',
    pureVeg: true,
    featuredTags: ['healthy', 'fitness', 'veg', 'lower-sugar', 'dairy-free', 'gluten-free'],
    menuCategories: ['Signature Bowls', 'Artisan Toasties', 'Super Smoothies', 'Fresh Soups', 'High Protein Platters'],
    phone: '+91 471 231 4455',
    reviews: [
      {
        id: 'rev-3',
        userName: 'Maya Pillai',
        rating: 5,
        date: '2 days ago',
        comment: 'The Avocado & Roasted Chickpea bowl is divine! No heavy oils, just clean crisp tastes.',
        foodItemName: 'Avocado Quinoa Garden Feast',
        helpfulCount: 19
      }
    ],
    menu: [
      {
        id: 'item-avocado-quinoa-bowl',
        restaurantId: 'rest-kowdiar-green-leaf-organics',
        restaurantName: 'Green Leaf Botanica & Cafe',
        name: 'Avocado Quinoa Garden Feast',
        description: 'Hass avocado slices, organic tri-color quinoa, charred corn, edamame and lemon-tahini dressing.',
        price: 289,
        originalPrice: 320,
        image: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=600&auto=format&fit=crop&q=80',
        isVeg: true,
        isBestseller: true,
        isQuick15: true,
        prepTimeMinutes: 10,
        rating: 4.9,
        ratingCount: 410,
        category: 'Signature Bowls',
        cuisine: 'Healthy Continental',
        tags: ['healthy', 'fitness', 'veg', 'gluten-free', 'dairy-free', 'less-oil', 'lower-sodium'],
        spiceLevel: 1,
        nutrition: {
          calories: 340,
          proteinGrams: 16,
          carbsGrams: 42,
          fatGrams: 14,
          fiberGrams: 11,
          sugarGrams: 2,
          sodiumMg: 210
        },
        available: true
      },
      {
        id: 'item-tofu-protein-power-salad',
        restaurantId: 'rest-kowdiar-green-leaf-organics',
        restaurantName: 'Green Leaf Botanica & Cafe',
        name: 'Smoked Tofu High-Protein Crunch',
        description: 'Pan-tossed high-protein herb tofu, roasted pumpkin seeds, microgreens, cucumber ribbons and apple cider vinaigrette.',
        price: 239,
        image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=600&auto=format&fit=crop&q=80',
        isVeg: true,
        isBestseller: false,
        isQuick15: true,
        prepTimeMinutes: 9,
        rating: 4.8,
        ratingCount: 290,
        category: 'High Protein Platters',
        cuisine: 'Healthy Continental',
        tags: ['high-protein', 'fitness', 'healthy', 'veg', 'dairy-free', 'less-oil', 'lower-sugar'],
        spiceLevel: 1,
        nutrition: {
          calories: 290,
          proteinGrams: 26,
          carbsGrams: 18,
          fatGrams: 8,
          fiberGrams: 7
        },
        available: true
      },
      {
        id: 'item-wild-berry-chia-smoothie',
        restaurantId: 'rest-kowdiar-green-leaf-organics',
        restaurantName: 'Green Leaf Botanica & Cafe',
        name: 'Wild Berry Chia Smoothie Jar (Zero Sugar)',
        description: 'Blueberries, strawberries, soaked chia seeds and unsweetened almond milk. Naturally sweetened with whole dates.',
        price: 169,
        image: 'https://images.unsplash.com/photo-1553530666-ba11a7da3888?w=600&auto=format&fit=crop&q=80',
        isVeg: true,
        isBestseller: true,
        isQuick15: true,
        prepTimeMinutes: 5,
        rating: 4.9,
        ratingCount: 360,
        category: 'Super Smoothies',
        cuisine: 'Beverages',
        tags: ['healthy', 'lower-sugar', 'dairy-free', 'gluten-free', 'veg', 'quick15'],
        spiceLevel: 1,
        nutrition: {
          calories: 180,
          proteinGrams: 6,
          carbsGrams: 28,
          fatGrams: 4,
          sugarGrams: 8
        },
        available: true
      }
    ]
  },
  {
    id: 'rest-palayam-sadhya-heritage',
    name: 'Travancore Grand Sadhya & Tiffin House',
    tagline: 'Authentic 18-Curry Sadhya, Steamed Idiyappam & Nadan Flavours',
    coverImage: 'https://images.unsplash.com/photo-1610057099443-fde8c4d50f91?w=1000&auto=format&fit=crop&q=80',
    logo: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=200&auto=format&fit=crop&q=80',
    isPartner: true,
    cuisines: ['Kerala Sadhya', 'Vegetarian', 'Traditional Tiffin'],
    rating: 4.7,
    ratingCount: 2310,
    area: 'Palayam & Central TVM',
    address: 'Near Statue Junction, MG Road, Palayam, Thiruvananthapuram',
    district: 'Thiruvananthapuram',
    lat: 8.5061,
    lng: 76.9525,
    distanceKm: 3.4,
    avgPrepTimeMin: 10,
    avgDeliveryTimeMin: 20,
    priceForTwo: 280,
    isOpen: true,
    openingHours: '7:00 AM - 10:00 PM',
    pureVeg: true,
    featuredTags: ['kerala-favs', 'veg', 'budget', 'family-meals', 'breakfast', 'lunch'],
    menuCategories: ['Grand Sadhya Meals', 'Steamed Tiffin', 'Nadan Curries', 'Chaya & Evening Snacks'],
    phone: '+91 471 247 1212',
    reviews: [
      {
        id: 'rev-4',
        userName: 'Gopakumar K.',
        rating: 5,
        date: '1 week ago',
        comment: 'Pure nostalgia! The Aviyal and Sambar are prepared with authentic Travancore temple-style spices.',
        foodItemName: 'Travancore Royal Banana Leaf Sadhya Box',
        helpfulCount: 42
      }
    ],
    menu: [
      {
        id: 'item-royal-sadhya-box',
        restaurantId: 'rest-palayam-sadhya-heritage',
        restaurantName: 'Travancore Grand Sadhya & Tiffin House',
        name: 'Travancore Royal Banana Leaf Sadhya Box',
        description: 'Complete feast: Kerala Matta rice, Sambhar, Parippu with Ghee, Aviyal, Thoran, Olan, Kalan, Inji Puli, Papadum, Payasam & Banana leaf packaging.',
        price: 199,
        originalPrice: 240,
        image: 'https://images.unsplash.com/photo-1610057099443-fde8c4d50f91?w=600&auto=format&fit=crop&q=80',
        isVeg: true,
        isBestseller: true,
        isQuick15: false,
        prepTimeMinutes: 10,
        rating: 4.9,
        ratingCount: 1250,
        category: 'Grand Sadhya Meals',
        cuisine: 'Kerala Sadhya',
        tags: ['kerala-favs', 'veg', 'family-meals', 'lunch', 'budget'],
        spiceLevel: 2,
        nutrition: {
          calories: 680,
          proteinGrams: 18,
          carbsGrams: 110,
          fatGrams: 16
        },
        available: true
      },
      {
        id: 'item-puttu-kadala-combo',
        restaurantId: 'rest-palayam-sadhya-heritage',
        restaurantName: 'Travancore Grand Sadhya & Tiffin House',
        name: 'Steamed Rice Puttu with Spiced Kadala Curry',
        description: 'Layered coconut & rice steamed cylinders paired with slow-simmered black chickpeas and roasted coconut gravy.',
        price: 99,
        originalPrice: 120,
        image: 'https://images.unsplash.com/photo-1516714435131-44d6b64dc6a2?w=600&auto=format&fit=crop&q=80',
        isVeg: true,
        isBestseller: true,
        isQuick15: true,
        prepTimeMinutes: 8,
        rating: 4.8,
        ratingCount: 780,
        category: 'Steamed Tiffin',
        cuisine: 'Kerala Traditional',
        tags: ['budget', 'kerala-favs', 'veg', 'high-protein', 'breakfast', 'less-oil', 'quick15'],
        spiceLevel: 2,
        nutrition: {
          calories: 360,
          proteinGrams: 14,
          carbsGrams: 64,
          fatGrams: 5,
          fiberGrams: 9
        },
        available: true
      },
      {
        id: 'item-pazham-pori-chaya',
        restaurantId: 'rest-palayam-sadhya-heritage',
        restaurantName: 'Travancore Grand Sadhya & Tiffin House',
        name: 'Crispy Nendran Pazham Pori (3 Pcs) & Sulaimani Tea',
        description: 'Golden ripe plantain fritters served with aromatic cardamom clove Sulaimani black tea.',
        price: 79,
        image: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=600&auto=format&fit=crop&q=80',
        isVeg: true,
        isBestseller: false,
        isQuick15: true,
        prepTimeMinutes: 6,
        rating: 4.7,
        ratingCount: 450,
        category: 'Chaya & Evening Snacks',
        cuisine: 'Kerala Snacks',
        tags: ['tea-snacks', 'budget', 'veg', 'comfort-food', 'quick15'],
        spiceLevel: 1,
        nutrition: {
          calories: 260,
          proteinGrams: 3,
          carbsGrams: 45,
          fatGrams: 8
        },
        available: true
      }
    ]
  },
  {
    id: 'rest-pattom-thalassery-biryani',
    name: 'Thalassery Spice House & Dum Biryani',
    tagline: 'Authentic Kaima/Jeerakasala Dum Biryani & Thalassery Delicacies',
    coverImage: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=1000&auto=format&fit=crop&q=80',
    logo: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=200&auto=format&fit=crop&q=80',
    isPartner: true,
    cuisines: ['Malabar Biryani', 'Mughlai', 'Kerala Non-Veg'],
    rating: 4.8,
    ratingCount: 3100,
    area: 'Pattom & Kesavadasapuram',
    address: 'Near Pattom Palace Junction, Thiruvananthapuram',
    district: 'Thiruvananthapuram',
    lat: 8.5284,
    lng: 76.9429,
    distanceKm: 2.8,
    avgPrepTimeMin: 12,
    avgDeliveryTimeMin: 22,
    priceForTwo: 380,
    isOpen: true,
    openingHours: '11:30 AM - 11:00 PM',
    pureVeg: false,
    featuredTags: ['kerala-favs', 'comfort-food', 'family-meals', 'lunch', 'dinner'],
    menuCategories: ['Dum Biryani Special', 'Starters & Grills', 'Malabar Breads', 'Desserts'],
    phone: '+91 471 244 8877',
    reviews: [
      {
        id: 'rev-5',
        userName: 'Fathima Raheem',
        rating: 5,
        date: '3 days ago',
        comment: 'Fragrant Kaima rice with tender chicken pieces that melt in your mouth. Accompanied with date pickle and coconut chammanthi!',
        foodItemName: 'Authentic Thalassery Chicken Dum Biryani',
        helpfulCount: 35
      }
    ],
    menu: [
      {
        id: 'item-thalassery-chicken-biryani',
        restaurantId: 'rest-pattom-thalassery-biryani',
        restaurantName: 'Thalassery Spice House & Dum Biryani',
        name: 'Authentic Thalassery Chicken Dum Biryani',
        description: 'Short grain Jeerakasala rice cooked on slow dum with aromatic ghee, fried onions, raisins, cashews and tender marinated country chicken.',
        price: 229,
        originalPrice: 260,
        image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=600&auto=format&fit=crop&q=80',
        isVeg: false,
        isBestseller: true,
        isQuick15: true,
        prepTimeMinutes: 10,
        rating: 4.9,
        ratingCount: 1800,
        category: 'Dum Biryani Special',
        cuisine: 'Malabar Biryani',
        tags: ['kerala-favs', 'comfort-food', 'family-meals', 'high-protein', 'lunch', 'dinner'],
        spiceLevel: 2,
        nutrition: {
          calories: 590,
          proteinGrams: 32,
          carbsGrams: 68,
          fatGrams: 20
        },
        available: true
      },
      {
        id: 'item-malabar-chicken-65',
        restaurantId: 'rest-pattom-thalassery-biryani',
        restaurantName: 'Thalassery Spice House & Dum Biryani',
        name: 'Crispy Curry Leaf Chicken 65',
        description: 'Crispy boneless chicken bites tossed with fresh curry leaves, green chillies and roasted crushed coriander.',
        price: 189,
        image: 'https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?w=600&auto=format&fit=crop&q=80',
        isVeg: false,
        isBestseller: true,
        isQuick15: true,
        prepTimeMinutes: 8,
        rating: 4.8,
        ratingCount: 620,
        category: 'Starters & Grills',
        cuisine: 'Kerala Non-Veg',
        tags: ['spicy-lovers', 'high-protein', 'comfort-food', 'quick15'],
        spiceLevel: 3,
        nutrition: {
          calories: 340,
          proteinGrams: 28,
          carbsGrams: 10,
          fatGrams: 18
        },
        available: true
      }
    ]
  },
  {
    id: 'rest-varkala-cliff-ocean-grill',
    name: 'Cliffside Ocean Grill & Cafe',
    tagline: 'Woodfired Artisan Crusts, Fresh Catch & Sunset Smoothies',
    coverImage: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1000&auto=format&fit=crop&q=80',
    logo: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=200&auto=format&fit=crop&q=80',
    isPartner: true,
    cuisines: ['Woodfired Pizza', 'Continental Seafood', 'Smoothie Bowls'],
    rating: 4.8,
    ratingCount: 820,
    area: 'Varkala Cliff & Helipad',
    address: 'North Cliff, Varkala, Thiruvananthapuram',
    district: 'Thiruvananthapuram',
    lat: 8.7379,
    lng: 76.7163,
    distanceKm: 8.2,
    avgPrepTimeMin: 18,
    avgDeliveryTimeMin: 28,
    priceForTwo: 550,
    isOpen: true,
    openingHours: '9:00 AM - 11:30 PM',
    pureVeg: false,
    featuredTags: ['comfort-food', 'dinner', 'late-night'],
    menuCategories: ['Artisan Woodfired Pizzas', 'Fresh Coastal Catch', 'Pasta & Risotto', 'Cold Squeezes'],
    phone: '+91 470 260 3344',
    reviews: [
      {
        id: 'rev-6',
        userName: 'Nicolette S. (Digital Nomad)',
        rating: 5,
        date: '4 days ago',
        comment: 'Best sourdough sourdough crust pizza in Kerala. Sourced with local basil and bocconcini.',
        foodItemName: 'Burrata & Wild Rocket Woodfired Pizza',
        helpfulCount: 16
      }
    ],
    menu: [
      {
        id: 'item-burrata-woodfired-pizza',
        restaurantId: 'rest-varkala-cliff-ocean-grill',
        restaurantName: 'Cliffside Ocean Grill & Cafe',
        name: 'Burrata & Wild Rocket Woodfired Pizza (11-inch)',
        description: '48-hour fermented sourdough crust, San Marzano tomato sauce, fresh creamy burrata, cherry tomatoes and wild rocket leaves.',
        price: 369,
        originalPrice: 420,
        image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=600&auto=format&fit=crop&q=80',
        isVeg: true,
        isBestseller: true,
        isQuick15: false,
        prepTimeMinutes: 16,
        rating: 4.9,
        ratingCount: 390,
        category: 'Artisan Woodfired Pizzas',
        cuisine: 'Woodfired Pizza',
        tags: ['comfort-food', 'veg', 'dinner', 'late-night'],
        spiceLevel: 1,
        nutrition: {
          calories: 640,
          proteinGrams: 24,
          carbsGrams: 76,
          fatGrams: 26
        },
        available: true
      },
      {
        id: 'item-pan-seared-prawns',
        restaurantId: 'rest-varkala-cliff-ocean-grill',
        restaurantName: 'Cliffside Ocean Grill & Cafe',
        name: 'Butter Garlic Herb Arabian Sea Prawns',
        description: 'Jumbo prawns pan-seared with garlic, extra virgin olive oil, chili flakes and fresh parsley.',
        price: 349,
        image: 'https://images.unsplash.com/photo-1565680018434-b513d5e5fd47?w=600&auto=format&fit=crop&q=80',
        isVeg: false,
        isBestseller: true,
        isQuick15: true,
        prepTimeMinutes: 12,
        rating: 4.8,
        ratingCount: 280,
        category: 'Fresh Coastal Catch',
        cuisine: 'Continental Seafood',
        tags: ['high-protein', 'gluten-free', 'dinner'],
        spiceLevel: 2,
        nutrition: {
          calories: 280,
          proteinGrams: 32,
          carbsGrams: 4,
          fatGrams: 14
        },
        available: true
      }
    ]
  },
  {
    id: 'rest-sreekaryam-fit-kitchen',
    name: 'NutriBite & High Protein Kitchen',
    tagline: 'Macro-Tracked Fitness Meals, Lean Meats & Carb-Controlled Platters',
    coverImage: 'https://images.unsplash.com/photo-1490645935967-10de6ba17061?w=1000&auto=format&fit=crop&q=80',
    logo: 'https://images.unsplash.com/photo-1490645935967-10de6ba17061?w=200&auto=format&fit=crop&q=80',
    isPartner: true,
    cuisines: ['Macro-Tracked Meals', 'Gym Bowls', 'Low-Carb'],
    rating: 4.9,
    ratingCount: 1120,
    area: 'Sreekaryam & Ulloor',
    address: 'Near CET Campus Gate, Sreekaryam, Thiruvananthapuram',
    district: 'Thiruvananthapuram',
    lat: 8.5471,
    lng: 76.9168,
    distanceKm: 2.5,
    avgPrepTimeMin: 11,
    avgDeliveryTimeMin: 19,
    priceForTwo: 320,
    isOpen: true,
    openingHours: '8:00 AM - 10:30 PM',
    pureVeg: false,
    featuredTags: ['fitness', 'high-protein', 'healthy', 'less-oil', 'lower-sugar'],
    menuCategories: ['50g+ Protein Bowls', 'Keto & Low Carb', 'Protein Wraps', 'Electrolyte & Whey Shakes'],
    phone: '+91 471 259 0011',
    reviews: [
      {
        id: 'rev-7',
        userName: 'Rahul K. (Fitness Trainer)',
        rating: 5,
        date: 'Yesterday',
        comment: 'Every calorie is verified. 48g protein bowl for under ₹250 is unbeatable in Trivandrum.',
        foodItemName: 'Triple Chicken & Egg Keto Shred Box',
        helpfulCount: 29
      }
    ],
    menu: [
      {
        id: 'item-shred-box',
        restaurantId: 'rest-sreekaryam-fit-kitchen',
        restaurantName: 'NutriBite & High Protein Kitchen',
        name: 'Triple Chicken & Egg Keto Shred Box',
        description: '200g herb grilled chicken breast, 2 boiled eggs, sautéed zucchini, spinach, roasted almonds and garlic olive oil dressing.',
        price: 259,
        originalPrice: 299,
        image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=600&auto=format&fit=crop&q=80',
        isVeg: false,
        isBestseller: true,
        isQuick15: true,
        prepTimeMinutes: 10,
        rating: 4.9,
        ratingCount: 620,
        category: '50g+ Protein Bowls',
        cuisine: 'Macro-Tracked Meals',
        tags: ['fitness', 'high-protein', 'healthy', 'less-oil', 'lower-sugar', 'gluten-free', 'quick15'],
        spiceLevel: 2,
        nutrition: {
          calories: 460,
          proteinGrams: 52,
          carbsGrams: 9,
          fatGrams: 18,
          fiberGrams: 5,
          sugarGrams: 2,
          sodiumMg: 310
        },
        available: true
      },
      {
        id: 'item-paneer-whey-wrap',
        restaurantId: 'rest-sreekaryam-fit-kitchen',
        restaurantName: 'NutriBite & High Protein Kitchen',
        name: 'Char-Grilled Cottage Cheese Protein Wrap',
        description: 'Whole wheat high-fiber wrap packed with 150g grilled cottage cheese, bell peppers, mint yogurt spread and flax seeds.',
        price: 179,
        image: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=600&auto=format&fit=crop&q=80',
        isVeg: true,
        isBestseller: true,
        isQuick15: true,
        prepTimeMinutes: 8,
        rating: 4.8,
        ratingCount: 390,
        category: 'Protein Wraps',
        cuisine: 'Healthy Wrap',
        tags: ['fitness', 'high-protein', 'veg', 'healthy', 'budget', 'quick15'],
        spiceLevel: 2,
        nutrition: {
          calories: 360,
          proteinGrams: 24,
          carbsGrams: 34,
          fatGrams: 12
        },
        available: true
      }
    ]
  },
  // Discovered Nearby Food Places (Map Discovery Layer - clearly separated from Partners)
  {
    id: 'nearby-kovalam-seafood-hub',
    name: 'Kovalam Lighthouse Fishermen Shack',
    tagline: 'Discovered Local Landmark • Sunset Beach Catch',
    coverImage: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=1000&auto=format&fit=crop&q=80',
    logo: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=200&auto=format&fit=crop&q=80',
    isPartner: false, // Discovered Nearby Place
    cuisines: ['Fresh Tawa Fry', 'Coastal Fish', 'Crab Roast'],
    rating: 4.6,
    ratingCount: 650,
    area: 'Kovalam & Vizhinjam Port',
    address: 'Lighthouse Beach Road, Kovalam, Thiruvananthapuram',
    district: 'Thiruvananthapuram',
    lat: 8.4004,
    lng: 76.9787,
    distanceKm: 9.4,
    avgPrepTimeMin: 25,
    avgDeliveryTimeMin: 35,
    priceForTwo: 500,
    isOpen: true,
    openingHours: '12:00 PM - 10:00 PM',
    pureVeg: false,
    featuredTags: ['kerala-favs', 'dinner'],
    menuCategories: ['Discovered Local Specialties'],
    phone: '+91 471 248 0199',
    reviews: [],
    menu: []
  },
  {
    id: 'nearby-balaramapuram-bun-roast',
    name: 'Balaramapuram Night Street Tea & Bun Corner',
    tagline: 'Discovered Local Landmark • Midnight Chaya & Spicy Roast',
    coverImage: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=1000&auto=format&fit=crop&q=80',
    logo: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=200&auto=format&fit=crop&q=80',
    isPartner: false, // Discovered Nearby Place
    cuisines: ['Street Food', 'Tea & Snacks', 'Midnight Bites'],
    rating: 4.4,
    ratingCount: 310,
    area: 'Neyyattinkara & Balaramapuram',
    address: 'NH 66 Junction, Balaramapuram, Thiruvananthapuram',
    district: 'Thiruvananthapuram',
    lat: 8.4011,
    lng: 77.0858,
    distanceKm: 8.5,
    avgPrepTimeMin: 20,
    avgDeliveryTimeMin: 30,
    priceForTwo: 180,
    isOpen: true,
    openingHours: '4:00 PM - 2:00 AM',
    pureVeg: false,
    featuredTags: ['tea-snacks', 'late-night', 'budget'],
    menuCategories: ['Street Delicacies'],
    phone: '+91 471 222 9901',
    reviews: [],
    menu: []
  }
];

export const INITIAL_USER_PROFILE = {
  id: 'user-demo-tvm',
  name: 'Alex Thomas',
  email: 'alex.thomas@quickbite.tvm',
  phone: '+91 98470 12345',
  role: 'customer' as const,
  avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&auto=format&fit=crop&q=80',
  preferences: {
    dietType: 'all' as const,
    lifestyle: ['fitness', 'high-protein', 'quick15'],
    healthConcerns: ['less-oil', 'lower-sugar'],
    spiceTolerance: 'medium' as const,
    maxBudget: 350,
    favCuisines: ['Kerala Traditional', 'Grill', 'Salads']
  },
  savedAddresses: [
    {
      id: 'addr-techno',
      label: 'Work' as const,
      street: 'Bhavani Building, 3rd Floor, Technopark Phase 1',
      area: 'Technopark & Kazhakkoottam',
      district: 'Thiruvananthapuram',
      landmark: 'Near Main Gate',
      lat: 8.5582,
      lng: 76.8812,
      isDefault: true
    },
    {
      id: 'addr-kowdiar',
      label: 'Home' as const,
      street: 'Villa 4, Golf Links Enclave, Kowdiar',
      area: 'Kowdiar & Vellayambalam',
      district: 'Thiruvananthapuram',
      landmark: 'Behind Kowdiar Palace',
      lat: 8.5241,
      lng: 76.9582,
      isDefault: false
    }
  ],
  defaultAddressId: 'addr-techno'
};
